UserCenter/Controllers/SubSystemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UserCenter.Controllers
{
    public class SubSystemController : Controller
    {
        //
        // GET: /BackGround/

        public ActionResult Index()
        {
            return View();
        }

        //
        // GET: /BackGround/Details/5

        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /BackGround/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /BackGround/Create

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /BackGround/Edit/5

        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /BackGround/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /BackGround/Delete/5

        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /BackGround/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

UserCenter/Views/Shared/_Confirm.cshtml
<div class="modal fade" id="confirm", data-bind="with: confirm">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 class="modal-title" data-bind="text: title"></h4>
			</div>
			<div class="modal-body">
				<p data-bind="text: content"></p>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal" data-bind="click: cancel">关闭</button>
				<button type="button" class="btn btn-primary" data-dismiss="modal" data-bind="click: confirm">确认</button>
			</div>
		</div>
	</div>
</div>

UserCenter/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="zh">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <meta charset="utf-8" />
        <title>@ViewBag.Title</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/bootstrap/all")
        @Styles.Render("~/Content/themes/flat-ui/css/all")
        @Styles.Render("~/Content/themes/messenger/all")
        @Styles.Render("~/Content/themes/messenger/messenger-theme-air.css")
        @Styles.Render("~/Content/css")
    </head>
    <body>
        <section>
            <head>
                <div class="navbar navbar-inverse navbar-static-top">
                    <div class="navbar-header">
                        @Html.ActionLink("用户中心", "Index", "Home", new {}, new { @class = "navbar-brand"})
                        <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".navbar-collapse-01"></button>
                    </div>
                    <div class="navbar-collapse collapse navbar-collapse-01">
                        <ul class="nav navbar-nav">
                            <li>
                                <a href="#">子系统</a>
                                <ul>
                                    <li>@Html.ActionLink("子系统管理", "Index", "SubSystem")</li>
                                </ul>
                            </li>
                            <li>
                                <a href="#"><span class="fui-user"></span></a>
                                <ul>
                                    <li>@using (Html.BeginForm("LogOff", "Account", new { area = "" }, FormMethod.Post, new { id = "logoutForm" })) {
                                            @Html.AntiForgeryToken()
                                            <a href="javascript:document.getElementById('logoutForm').submit()">登出</a>
                                        }
                                    </li>
                                </ul>
                            </li>
                        </ul>
                        <ul class="nav navbar-nav navbar-right">
                            <li><a id="todotrigger" href="#"><span class="fui-list"></span></a></li>
                        </ul>
                    </div>
                </div>
            </head>
            <body>
                @RenderBody()
            </body>
        </section>
        @RenderSection("modal", required: false)
        @Scripts.Render("~/bundles/lib")
        @RenderSection("scripts", required: false)
    </body>
</html>

UserCenter/Views/Shared/_Pagination.cshtml
<div class="pagination" data-bind="with: pagination, visible: pagination.totalPage() > 1">
	<ul>
	  <!-- ko foreach: pages -->
	  <li data-bind="css: {active: index == $parent.currentPage(), previous: ($data.arrowLeft), next: ($data.arrowRight)}">
	  	<a href="#" data-bind="text: content, click: $parent.changePage.bind($parent), css: {'fui-arrow-left': ($data.arrowLeft), 'fui-arrow-right': ($data.arrowRight)}"></a>
	  </li>
	  <!-- /ko -->
	</ul>
</div>